# ----
# Site

title: ForgeRock Identity Cloud Early Access Program
url: "https://forgecloud.github.io/"
baseurl:
google_analytics_key:
show_full_navigation: false #toggle to show all nav groups or only active group

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: EA Developer documentation for ForgeRock Idenity cloud platform.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: ForgeRock Docs
  links:
    - https://github.com/ForgeCloud/forgecloud.github.io

# -----
# Build

permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-octicons
  - jekyll-plantuml

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - license
  - ci/

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
